### Create a new user
POST http://localhost:3003/admin/users
content-type: application/json

{
    "email": "comum@comum.com",
    "password": "Bielf1234-",
    "nome_completo": "comum da silva",
    "data_nasc": "1990-01-01",
    "genero": "m",
    "tipo_usuario": "comum",
    "funcao": "Padre",
    "num_documento": "1234567890",
    "tipo_documento": "cpf",
    "avatar_image_data": "https://static.vecteezy.com/ti/fotos-gratis/t1/6847951-headshot-retrato-de-homem-senior-no-armazem-idoso-caucasiano-velho-foto.jpg"
}